from urllib.request import urlopen
import sys

def square(x):
    return x * x

def get_temperature(city):
    url = "https://wttr.in/" + city + "?format=%t"
    page = urlopen(url)
    raw = page.read()
    temp = raw.decode("utf-8")
    return temp

def main():
    if len(sys.argv) != 2:
        print("Usage: python script.py <city>")
        sys.exit(1)
    
    city = sys.argv[1]
    temp = get_temperature(city)
    print(temp)

if __name__ == "__main__":
    main()
